### ISSUE TITLE
reboot feature no longer work

### ISSUE THREAD

**Issue by yoho2chn** [Pzqqt/Magisk_Manager_Recovery_Tool#1]
May be because of the TWRP note has individual switch for reboot after zip installation complete

**Comment by Pzqqt** [comment]
When you select the "Reboot" option, the installer will exit to Recovery instead of reboot, right?

**Comment by Pzqqt** [comment]
> May be because of the TWRP note has individual switch for reboot after zip installation complete

When you select the "Reboot" option, the installer will exit to Recovery instead of reboot, right? I think it's a TWRP bug, or maybe Aroma Installer is not compatible with your device.
