### ISSUE TITLE
红米k40p  twrp3.60  卡死

### ISSUE THREAD

**Issue by xiang473535976** [Pzqqt/Magisk_Manager_Recovery_Tool#10]
请大佬适配下  安卓12  谢谢 这个工具一直很好用  感谢

**Comment by Pzqqt** [comment]
> 请大佬适配下 安卓12 谢谢 这个工具一直很好用 感谢

卡死问题是Aroma Installer的缺陷，简单来说，是Aroma Installer的图形渲染驱动不支持更新的图形渲染方式。

目前使用较新的高通Soc设备都会卡死（不清楚联发科的情况），作为一个参考，骁龙660以及之前出的Soc不会有卡死的问题。

Aroma Installer已年久失修，我无法修复。
