### ISSUE TITLE
Is there any way to make it work with TWRP? 

### ISSUE THREAD

**Issue by M7amma** [Pzqqt/Magisk_Manager_Recovery_Tool#12]
And if it's not possible, is there a similar module that works with TWRP in recovery?

**Comment by Pzqqt** [comment]
> And if it's not possible, is there a similar module that works with TWRP in recovery?

It supports TWRP. If you get stuck after flashing it, your device is not compatible with Aroma Installer. See [this issue](https://github.com/amarullz/AROMA-Installer/issues/38)
