### ISSUE TITLE
支持 Android 12 吗？是否只支持twrp刷入？adb sideload可行吗？

### ISSUE THREAD

**Issue by davidlauhn** [Pzqqt/Magisk_Manager_Recovery_Tool#14]
刷的PEP，暂不支持第三方Rec

**Comment by Pzqqt** [comment]
> 刷的PEP，暂不支持第三方Rec

1. 这与你使用什么版本的Android系统没有关系。但是，使用本工具的前提是data分区未加密或data分区可以正常解密和挂载。
2. 当然支持TWRP，但是，Aroma可能不兼容你的设备，作为参考，高通660之后的6系列soc，高通所有7系列soc，高通835之后的所有8系列soc，是不支持的（刷入时会卡住，因为Aroma不能正常渲染画面，此时只能重启）。
3. adb sideload可行。
4. 我不清楚你在使用什么recovery，如果是TWRP及其衍生，理所当然是支持的，但如果是AOSP recovery，我也不清楚能否支持。

**Comment by davidlauhn** [comment]
了解了，谢谢
