### ISSUE TITLE
unzip error

### ISSUE THREAD

**Issue by Bluscream** [Pzqqt/Magisk_Manager_Recovery_Tool#15]
![Screenshot_2022-06-21-18-55-56-665](https://user-images.githubusercontent.com/3318223/174866856-d3a3dd50-1ef1-4559-8708-75b5bc41eb9c.jpeg)

**Comment by Pzqqt** [comment]
No one has ever told you that this is a Magisk module.

**Comment by Bluscream** [comment]
What else would it be? It's not an APK

**Comment by Pzqqt** [comment]
> What else would it be? It's not an APK

Flash it in recovery. See https://forum.xda-developers.com/t/tool-aroma-magisk-manager-recovery-tool-v2-4.3866502

**Comment by Bluscream** [comment]
Ohh i see. Thank you ^^ do you know why it only shows 1 module (fdroid extension) while it says i have 6 modules installed in lsposed
