### ISSUE TITLE
Pixel 7 Pro Error upacking zip

### ISSUE THREAD

**Issue by ZerkerEOD** [Pzqqt/Magisk_Manager_Recovery_Tool#18]
As the title says, I am getting an error to unpack zip. Other modules have no issues.

**Comment by Pzqqt** [comment]
0. Please read the readme.md carefully.
1. No one has ever told you that this is a Magisk module.
2. You can only use it in custom recovery.
3. Your device is so new that this tool may not be compatible with your device.

**Comment by ZerkerEOD** [comment]
@Pzqqt, sorry for that. I read the readme this time and see that it doesn't say its a magisk module. However, when I googled best magisk modules, this pops up very often, leading everyone to believe it is an actual module. So, a lot of people have stated its a module, just not you.

**Comment by Pzqqt** [comment]
> @Pzqqt, sorry for that. I read the readme this time and see that it doesn't say its a magisk module. However, when I googled best magisk modules, this pops up very often, leading everyone to believe it is an actual module. So, a lot of people have stated its a module, just not you.

Hmmm, I don't even know when they started promoting this.😅

**Comment by ZerkerEOD** [comment]
No worries, thanks for letting me know though the proper way to install.
