### ISSUE TITLE
MMRT 2.5 not working, while MMRT 2.4 still works

### ISSUE THREAD

**Issue by sn-o-w** [Pzqqt/Magisk_Manager_Recovery_Tool#19]
Hi,

For some reason, latest version doesn't want to work on a Nexus 5 running on Android 10.

<img src="https://user-images.githubusercontent.com/2406819/201131972-fc399d07-172a-4a77-af13-94212c210787.png" width=50% height=50%>

My device has TWRP 3.7.0

MMRT 2.4 seems to be fine tho.

**Comment by Pzqqt** [comment]
Give me recovery logs.

**Comment by sn-o-w** [comment]
@Pzqqt Sure. Hope these logs are useful.

[dmesg.log](https://github.com/Pzqqt/Magisk_Manager_Recovery_Tool/files/9991723/dmesg.log)
[logcat.txt](https://github.com/Pzqqt/Magisk_Manager_Recovery_Tool/files/9991724/logcat.txt)
[recovery.log](https://github.com/Pzqqt/Magisk_Manager_Recovery_Tool/files/9991725/recovery.log)

**Comment by Pzqqt** [comment]
> @Pzqqt Sure. Hope these logs are useful.
> 
> [dmesg.log](https://github.com/Pzqqt/Magisk_Manager_Recovery_Tool/files/9991723/dmesg.log) [logcat.txt](https://github.com/Pzqqt/Magisk_Manager_Recovery_Tool/files/9991724/logcat.txt) [recovery.log](https://github.com/Pzqqt/Magisk_Manager_Recovery_Tool/files/9991725/recovery.log)

You may be using random package name for Magisk app, I have found the reason, will fix in next version.

**Comment by Pzqqt** [comment]
@sn-o-w Try this build.

[EN_MMRT-v2.5-Beta2.zip](https://github.com/Pzqqt/Magisk_Manager_Recovery_Tool/files/9994375/EN_MMRT-v2.5-Beta2.zip)

**Comment by sn-o-w** [comment]
You are right, I use random package name for Magisk.

`EN_MMRT-v2.5-Beta2` seems to work well, I can see AROMA showing up, no more errors. 😊
