### ISSUE TITLE
不能在twrp里面刷入吗？刷到一半就卡死了

### ISSUE THREAD

**Issue by zhang-001** [Pzqqt/Magisk_Manager_Recovery_Tool#4]
不能在twrp里面刷入吗？刷到一半就卡死了

**Comment by Pzqqt** [comment]
> 不能在twrp里面刷入吗？刷到一半就卡死了

该工具本质上就是一个卡刷包 你只能在Recovery刷入 至于卡死问题 请认真阅读README
